services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../:/app/:ro
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    restart: always
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    build:
      context: php-fpm
      args:
        USER_ID: "${UID}"
    volumes:
      - ../../:/app
      - composer:/var/www/.composer:rw
      - $SSH_AUTH_SOCK:/ssh-agent
    restart: always
    depends_on:
      - db_asia
      - db_america
      - db_europe
    environment:
       SSH_AUTH_SOCK: /ssh-agent
       SSH_AGENT_PID: $SSH_AGENT_PID
       APPLICATION_ENV: production
       PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /app

  cron:
    tty: true # Enables debugging capabilities when attached to this container.
    build: ./cron
    volumes:
      - ../../:/app
    restart: always
    environment:
      APPLICATION_ENV: production
    depends_on:
      - db_asia
      - db_america
      - db_europe
    working_dir: /app

  node:
    build:
      context: node
      args:
        USER_ID: "${UID}"
    volumes:
      - ../../:/app
    restart: always
    ports:
      - '3000:3000'
      - '3001:3001'
    links:
      - nginx
    working_dir: /app
    entrypoint: ['tail', '-f', '/dev/null']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db_europe
    environment:
      PMA_HOSTS: db_america, db_asia, db_europe
      PMA_PORT: 3306
    ports:
      - "8081:80"

  db_america:
    image: mariadb
    env_file: ../../.env
    volumes:
      - db_data_america:/var/lib/mysql
      - ./../america/PriceEntity.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
    restart: always

  db_asia:
    image: mariadb
    env_file: ../../.env
    volumes:
      - db_data_asia:/var/lib/mysql
      - ./../asia/PriceEntity.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
    restart: always

  db_europe:
    image: mariadb
    env_file: ../../.env
    volumes:
      - db_data_europe:/var/lib/mysql
      - ./../europe/PriceEntity.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

volumes:
  composer:
  db_data_america:
  db_data_asia:
  db_data_europe:
