services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../:/app/:ro
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    ports:
      - "9003:9003"
    build:
      context: php-fpm
      args:
        USER_ID: "${UID}"
    volumes:
      - ../../:/app
      - composer:/var/www/.composer:rw
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - database
    environment:
       SSH_AUTH_SOCK: /ssh-agent
       SSH_AGENT_PID: $SSH_AGENT_PID
       APPLICATION_ENV: development
       PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /app

  cron:
    tty: true # Enables debugging capabilities when attached to this container.
    build: ./cron
    volumes:
      - ../../:/app
    restart: no
    environment:
      APPLICATION_ENV: development
    depends_on:
      - database
    working_dir: /app

  node:
    build:
      context: node
      args:
        USER_ID: "${UID}"
    volumes:
      - ../../:/app
    ports:
      - '3000:3000'
      - '3001:3001'
    links:
      - nginx
    working_dir: /app
    entrypoint: ['tail', '-f', '/dev/null']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: no
    depends_on:
      - database
    environment:
      PMA_HOSTS: database
      PMA_PORT: 3306
    ports:
      - "8081:80"

  database:
    image: mariadb
    env_file: database/database.env
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: no

volumes:
  composer:
  database_data:
